eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8764
spring:
  application:
    name: service-ribbon