eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    hostname: 127.0.0.1

server:
  port: 8762
spring:
  application:
    name: service-hi
